### ISSUE TITLE
Windows 2016+

### ISSUE THREAD

**Issue by wahmedswl** [Roblox/nomad-driver-iis#31]
Hi, is there any particular reason this driver only support Windows 2016+ or its just docs issue?

Thanks

**Comment by Vulfox** [comment]
@wahmedswl , I specifically chose Windows 2016+ to be supported as it is the current minimum Windows Server version that is not EOL'ed yet. I also want to rely on IIS 10 features, which started being installed for Windows 2016 machines.
I don't think the driver currently utilizes IIS 10 specific features yet, but there is work being done for another issue that would need to make use of IIS 10.

#30 
https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/environmentvariables/

However, I think this driver *could* work on an Windows2012R2 machine provided it does not use IIS 10 specific features.

To improve clarity on docs, I can add a list of nomad job spec -> IIS features with minimum supported version so that someone who wishes to use an older version of IIS/Windows can do so, but would require a bit more leg work with the app pool/site config xmls.

Thoughts?

**Comment by wahmedswl** [comment]
yes, if someone want to utilize some feature that's only supported in Windows 2016 then its ok but if some feature can work at lowest version then that should be supported.

Feature -> Window requirement is nice idea and it will add clarity 👍 

Thanks

**Comment by Vulfox** [comment]
Added the suggested documentation to the README. Each feature that this driver uses states the minimal viable version that IIS needs. I was able to test this against a 2012R2 machine and it worked fine. 2008 couldn't run nomad for me (without the driver). Anything older than 2008 tends to lose a lot of functionality with this driver and didn't test with those machine.
