### ISSUE TITLE
No output in Nomad allocation logs

### ISSUE THREAD

**Issue by cattuz** [Roblox/nomad-driver-iis#59]
I've recently set up the driver on a Nomad Client running Windows Server 2019. After adding IIS6 management compatibility (which is not enabled by default for IIS10, but seems to be required by the driver) tasks are running and working great!

However, I'm not seeing any log output from the driver at all. Neither errors (when I tried running without IIS6 compat) nor any informational messages appear in stdout or stderr. Am I missing some config or is this simply not implemented?

Looking at the source I would expect some log output, but I am not yet familiar enough with Nomad drivers to be sure.

Other tasks (powershell etc) running on the VM are logging fine by the way.

**Comment by Vulfox** [comment]
There is no default logging for this driver at this time. Due to the nature of IIS, I don't get stdout/err output from a running service and legacy Windows workflows tend to utilize Windows Event Logging. If you know of a good way to for a service to latch onto stdout/err on a running process within IIS, I am all ears.

I've got a thought on setting up a flat file tailing config and/or event log tailing, but haven't implemented on it yet. Cause logging is on the implementer of the service and IIS logging isn't uniform for all service. Though, there is also IIS logs in of themselves. Which do you think would be the more sensible logging for this driver for your use case?

`which is not enabled by default for IIS10, but seems to be required by the driver` This sounds like a bug 🤔 . I can try to run it against a Win2019 VM and see if I get this same error. My tests run against Win2016 (IIS10) via automation and Win2012R2 (for legacy fixes, manually). There might be a setting I am running to make Win2012R2 happy that makes Win2019 unhappy.

**Comment by cattuz** [comment]
> There is no default logging for this driver at this time.

Aha that explains it! I don't know what kind of output I expected to see in the logs to be honest. Just wanted to make sure I wasn't missing anything :)

> This sounds like a bug 🤔 . I can try to run it against a Win2019 VM and see if I get this same error.

I tried it with Windows server 2016 and have the same issue. It's an Azure VM using the following params:

> image_offer = "WindowsServer"
> image_publisher = "MicrosoftWindowsServer"
> image_sku = "2016-Datacenter"
> os_type = "Windows"

With the following script run on startup:

> Add-WindowsFeature Web-Server

After some experimentation, I found this command is required to make the driver work:

> Dism /Online /Enable-Feature /FeatureName:IIS-IIS6ManagementCompatibility

Maybe it's an Azure thing.

**Comment by Vulfox** [comment]
This definitely sounds like an Azure VM specific problem. I have used Windows 2016 default OS images via virtualbox for these tests with no problems. I am going to take a guess and assume the Azure VMs doesn't like the idea of automation using `appcmd.exe` calls, but I am not 100% on that.

It may be worth calling out that Azure VMs need to have the IIS6 compat feature enabled in the README.

**Comment by cattuz** [comment]
I'll do some more testing. I'm also having trouble with the TEMP environment variable not being set to the app pool user's temp dir. It works on my machine but on the VM using win_iis it's being set to the system temp dir. All the settings on the app pool look right in the IIS manager, but for some reason TEMP is still pointing to the wrong dir during runtime. My apppool's processmodel config:

`<processModel identityType="ApplicationPoolIdentity" loadUserProfile="true" setProfileEnvironment="true" />`

I'm suspecting this is related to having to enable IIS6-compatibility, so I'll do some more digging and see if I can't get to the bottom of it.

Thank you for this driver by the way! Other than the aforementioned it's working swimmingly :)

**Comment by Vulfox** [comment]
This is due to the driver injecting the environment variables available to the Nomad service (Windows SC). Because the `TEMP` env var is set as a system level configuration, it gets picked up as an env var that the driver should pass along to the the child tasks (win_iis tasks), which consequently overrides your AppPool temp env var.

A few of solutions would be to either always respect the AppPool's `TEMP` env var, allow user level overrides from the Nomad spec meta env settings, or have an allow/deny list config of env vars a user would want to have populated from Nomad to the AppPool.

`Thank you for this driver by the way! Other than the aforementioned it's working swimmingly :)` ❤️ 

If you feel like your questions have been adequately answered here and there is no need for a code change follow-up, I can close this issue.

**Comment by cattuz** [comment]
Sorry for the late reply. Yes, all my questions have been answered so go ahead and close it :)
